language: python
dist: xenial
sudo: required
cache:
  pip: true
branches:
  only:
  - master
addons:
  chrome: stable

matrix:
  fast_finish: true
  include:
    - python: '3.6.7'
      before_script:
        - sudo apt-get update
        - sudo apt-get install gcc libgraphviz-dev graphviz -y --fix-missing
        - sudo redis-server /etc/redis/redis.conf --port 6379
        - sudo apt-get install -y chromium-browser
        - sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1
        - wget http://chromedriver.storage.googleapis.com/2.35/chromedriver_linux64.zip
        - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.6.7/bin/
        - sudo chmod +x /home/travis/virtualenv/python3.6.7/bin/chromedriver
        - export CHROMEDRIVER=/home/travis/virtualenv/python3.6.7/bin/chromedriver
        - cd EDA_miner && python users_mgt.py && cd ..
      script:
        - cd tests && py.test .


before_install:
  - set -e

install:
  - pip install -r requirements.txt

script:
  - cd tests && py.test .
